baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "...Down the Rabbit Hole..."
author = "Miles Benton"
copyright = "&copy; 2017. All rights reserved."
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pagination = 10

[permalinks]
    post = "/:year/:month/:day/:slug/"
    projects = "/:filename/"
    workshops-tutorials = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-newspaper-o fa-fw'></i>"
    weight = -110    
    url = "/"
[[menu.main]]
    name = "Publications"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = -109
    url = "/publications/"
[[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-cogs fa-fw'></i>"
    weight = -110
    url = "/projects/"
[[menu.main]]
    name = "Tutorials"
    pre = "<i class='fa fa-question-circle fa-fw'></i>"
    weight = -110
    url = "/workshops-tutorials/"
[[menu.main]]
    name = "Presentations"
    pre = "<i class='fa fa-picture-o fa-fw'></i>"
    weight = -105
    url = "/presentations/"
[[menu.main]]
    name = "CV"
    pre = "<i class='fa fa-file-pdf-o fa-fw'></i>"
    weight = -100
    url = "/cv/cv_updated.pdf"    
[[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fa fa-github fa-fw'></i>"
    url = "https://github.com/sirselim"
[[menu.main]]
    name = "GoogleScholar"
    weight = -98
    pre = "<i class='ai ai-google-scholar fa-fw'></i>"
    url = "https://scholar.google.co.nz/citations?user=iEhBavEAAAAJ&hl=en" 
[[menu.main]]
    name = "ResearchGate"
    weight = -97
    pre = "<i class='ai ai-researchgate fa-fw'></i>"
    url = "https://www.researchgate.net/profile/Miles_Benton"
[[menu.main]]
    name = "LinkedIn"
    weight = -96    
    pre = "<i class='fa fa-linkedin-square fa-fw'></i>"
    url = "https://www.researchgate.net/profile/Miles_Benton"
[[menu.main]]
    name = "Twitter"
    weight = -95
    pre = "<i class='fa fa-twitter-square fa-fw'></i>"
    url = "https://twitter.com/miles_benton"
[[menu.main]]
    name = "ORCiD"
    weight = -94
    pre = "<i class='ai ai-orcid fa-fw'></i>"
    url = "http://orcid.org/0000-0003-3442-965X"
[[menu.main]]
    name = "Mendeley"
    weight = -93
    pre = "<i class='ai ai-mendeley fa-fw'></i>"
    url = "https://www.mendeley.com/profiles/miles-benton/"

[params]
    subtitle = "“If you don't know where you are going any road can take you there”"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
